export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const OTP_LOGIN_SUCCESS = "OTP_LOGIN_SUCCESS";
export const OTP_LOGIN_FAIL = "OTP_LOGIN_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const EMPTY_USER_SUCCESS = "EMPTY_USER_SUCCESS";
export const EMPTY_USER_FAIL = "EMPTY_USER_FAIL";

export const EDIT_INFO_OTP_SUCCESS = "EDIT_INFO_OTP_SUCCESS";
export const EDIT_INFO_OTP_FAIL = "EDIT_INFO_OTP_FAIL";

export const SET_TOKEN_IN_STATE = "SET_TOKEN_IN_STATE";
export const REMOVE_TOKEN_FROM_STATE = "REMOVE_TOKEN_FROM_STATE";
